export const photos = [
  {
    src: "/kilo.jpg",
    alt: "",
    description: "Kilolo",
    location: "Lagos, Nigeria",
    instagram: "https://instagram.com",
  },
  {
    src: "/skate.jpg",
    alt: "",
    description: "NINE SKATE JAM PARTY '25",
    location: "Lagos Nigeria",
    instagram: "https://instagram.com",
  },
  {
    src: "/money.jpg",
    alt: "",
    description: "NINE SKATE JAM PARTY '25",
    location: "Lagos, Nigeria",
    camera: "Fujifilm X-T4, 56mm f/1.2",
    instagram: "https://instagram.com",
  },
  {
    src: "/tolibian.jpg",
    alt: "",
    description:
      "Exclusive photos of Tolibian on set of the video shoot for his latest singe “LATANSA”",
    location: "Lagos, Nigeria",
    camera: "Nikon Z6 II, 14-24mm f/2.8",
    instagram: "https://instagram.com",
  },
  {
    src: "/bizzy.jpg",
    alt: "",
    description: "Shoot for Mavo Swago & Kashcoming",
    location: "Lagos, Nigeria",
    camera: "Sony A7R IV, 85mm f/1.4",
    instagram: "https://instagram.com",
  },
  {
    src: "/wande.jpg",
    alt: "",
    description: "Potraits of Miss Wande",
    location: "Lagos, Nigeria",
    camera: "Canon EOS R6, 100mm f/2.8 Macro",
    instagram: "https://instagram.com",
  },
  {
    src: "/skate2.jpg",
    alt: "",
    description: "Shoot for Nine Skate Jam 2025",
    location: "Lagos, Nigeria",
    camera: "Sony A7 III, 16-35mm f/2.8",
    instagram: "https://instagram.com",
  },
  {
    src: "/llygant.jpg",
    alt: "",
    description: "Shoot for LLYGANT",
    location: "Lagos, Nigeria",
    camera: "Fujifilm GFX 100S, 110mm f/2",
    instagram: "https://instagram.com",
  },
];
